name: Y - Do NOT Install - Testing - OnStar2MQTT Home Assistant Add-on (BigThunderSR) for Vehicle 1
version: 2.5.2
slug: y_test_onstar2mqtt_bigthundersr_vehicle1
description: Do NOT Install - Testing - Home Assistant Add On Version of BigThunderSR/onstar2mqtt for Vehicle 1
#codenotary: bigthundersr@outlook.com
#startup: application
#boot: auto
arch:
  - aarch64
  - amd64
map:
  - share:rw
  - ssl:rw
url: "https://github.com/BigThunderSR/homeassistant-addons-onstar2mqtt"
image: "ghcr.io/bigthundersr/test-ha-addons-onstar2mqtt-btsr-test2-veh1-{arch}"
services:
  - "mqtt:need"
init: false
options:
  LOG_LEVEL: "info"
  VEHICLE_NAME: "Vehicle 2"
  ONSTAR_DEVICEID: ""
  ONSTAR_VIN: ""
  ONSTAR_USERNAME: ""
  ONSTAR_PASSWORD: ""
  ONSTAR_TOTP: ""
  ONSTAR_PIN: ""
  TOKEN_LOCATION: "/ssl/vehicle1"
  ONSTAR_URL: "https://api.gm.com" #This value is hard coded in the program code and cannot be changed at this time
  ONSTAR_REFRESH: 1800000
  ONSTAR_RECALL_REFRESH: 604800000
  ONSTAR_POLL_INTERVAL: 6
  ONSTAR_POLL_TIMEOUT: 90
  ONSTAR_STATE_CACHE: false
  OPENID_CLOCK_TOLERANCE_SEC: 120
  MQTT_HOST: ""
  MQTT_USERNAME: ""
  MQTT_PASSWORD: ""
  MQTT_PORT: 1883
  MQTT_PREFIX: "homeassistant"
  MQTT_ONSTAR_POLLING_STATUS_TOPIC: "homeassistant/onstar2mqtt/vehicle2/polling"
  MQTT_LIST_ALL_SENSORS_TOGETHER: false
  MQTT_TLS: false
  MQTT_REJECT_UNAUTHORIZED: true
  MQTT_CA_FILE: ""
  MQTT_CERT_FILE: ""
  MQTT_KEY_FILE: ""
schema:
  LOG_LEVEL: str
  VEHICLE_NAME: str
  ONSTAR_DEVICEID: str
  ONSTAR_VIN: str
  ONSTAR_USERNAME: str
  ONSTAR_PASSWORD: password
  ONSTAR_TOTP: password
  ONSTAR_PIN: password
  TOKEN_LOCATION: str?
  ONSTAR_URL: str
  ONSTAR_REFRESH: int
  ONSTAR_RECALL_REFRESH: int
  ONSTAR_POLL_INTERVAL: int
  ONSTAR_POLL_TIMEOUT: int
  ONSTAR_STATE_CACHE: bool
  OPENID_CLOCK_TOLERANCE_SEC: int
  MQTT_HOST: str
  MQTT_USERNAME: str
  MQTT_PASSWORD: password
  MQTT_PORT: port
  MQTT_PREFIX: str
  MQTT_ONSTAR_POLLING_STATUS_TOPIC: str?
  MQTT_LIST_ALL_SENSORS_TOGETHER: bool
  MQTT_TLS: bool
  MQTT_REJECT_UNAUTHORIZED: bool
  MQTT_CA_FILE: str?
  MQTT_CERT_FILE: str?
  MQTT_KEY_FILE: str?
